### PR TITLE
Rename directories and move files

### PR DESCRIPTION
**Pull request by k-sharpe**
Not sure if this is expected but swapped some stuff around

### CODE REVIEW

**Comment by jennygaoo** [comment]
what's dto?

**Comment by k-sharpe** [comment]
if I change the package line in the files I get a bunch of import errors because the classes are in different directories (Ex: OrderProcessor in common not knowing what an Order is because it's in com.google.sps.dto) Should I add imports to all the files?

**Comment by jennygaoo** [comment]
> if I change the package line in the files I get a bunch of import errors because the classes are in different directories (Ex: OrderProcessor in common not knowing what an Order is because it's in com.google.sps.dto) Should I add imports to all the files?

yes

**Comment by andreahu12** [comment]
> what's dto?

we should try to avoid abbreviations in code. @k-sharpe could you clarify what DTO is?

**Comment by k-sharpe** [comment]
DTO was from our chat, data tranfer object

**Comment by andreahu12** [comment]
Could you update the formatting paths as well? Similar to https://github.com/googleinterns/step8-2020/pull/23/files

**Pull request merged**
